import { describe, it, expect } from 'vitest'
import { buildSystemPrompt } from '@/server/services/prompt-builder'
import type { BotConfig } from '@/types'

function makeBotConfig(overrides: Partial<BotConfig> = {}): BotConfig {
  return {
    id: 'test-bot-1',
    name: 'TestBot',
    description: 'A test bot for unit tests',
    businessType: 'restaurant',
    botLanguages: ['ru'],
    personality: 'friendly',
    welcomeMessage: 'Welcome!',
    workingHours: null,
    address: null,
    managerContact: null,
    telegramToken: 'fake-token',
    telegramBotName: 'test_bot',
    isActive: true,
    capabilities: [],
    products: [],
    faqItems: [],
    ...overrides,
  }
}

describe('Prompt Builder', () => {
  it('generates prompt with bot name', () => {
    const bot = makeBotConfig({ name: 'FlowerShop' })
    const prompt = buildSystemPrompt(bot)
    expect(prompt).toContain('FlowerShop')
  })

  it('includes personality instructions', () => {
    const formalBot = makeBotConfig({ personality: 'formal' })
    const formalPrompt = buildSystemPrompt(formalBot)
    expect(formalPrompt).toContain('ФОРМАЛЬНЫЙ')

    const funBot = makeBotConfig({ personality: 'fun' })
    const funPrompt = buildSystemPrompt(funBot)
    expect(funPrompt).toContain('ВЕСЁЛЫЙ')

    const friendlyBot = makeBotConfig({ personality: 'friendly' })
    const friendlyPrompt = buildSystemPrompt(friendlyBot)
    expect(friendlyPrompt).toContain('ДРУЖЕЛЮБНЫЙ')
  })

  it('includes product catalog', () => {
    const bot = makeBotConfig({
      products: [
        {
          id: 'p1',
          botId: 'test-bot-1',
          name: 'Плов',
          nameUz: 'Osh',
          description: 'Узбекский плов',
          price: 35000 as any,
          currency: 'UZS',
          category: 'Основные блюда',
          imageUrl: null,
          inStock: true,
          sortOrder: 0,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
      ],
    })
    const prompt = buildSystemPrompt(bot)
    expect(prompt).toContain('Каталог товаров')
    expect(prompt).toContain('Плов')
    expect(prompt).toContain('Osh')
    expect(prompt).toContain('Основные блюда')
  })

  it('includes FAQ items', () => {
    const bot = makeBotConfig({
      faqItems: [
        {
          id: 'f1',
          botId: 'test-bot-1',
          question: 'Как заказать?',
          questionUz: 'Qanday buyurtma beraman?',
          answer: 'Напишите нам',
          answerUz: 'Bizga yozing',
          isAutoGenerated: false,
          sortOrder: 0,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
      ],
    })
    const prompt = buildSystemPrompt(bot)
    expect(prompt).toContain('Часто задаваемые вопросы')
    expect(prompt).toContain('Как заказать?')
    expect(prompt).toContain('Напишите нам')
  })

  it('handles multi-language bots', () => {
    const bot = makeBotConfig({ botLanguages: ['ru', 'uz', 'en'] })
    const prompt = buildSystemPrompt(bot)
    expect(prompt).toContain('ru, uz, en')
    expect(prompt).toContain('Автоматически определяй язык')
  })

  it('handles single-language bots', () => {
    const bot = makeBotConfig({ botLanguages: ['uz'] })
    const prompt = buildSystemPrompt(bot)
    expect(prompt).toContain('узбекском')
    expect(prompt).not.toContain('Автоматически определяй язык')
  })

  it('includes order instructions when orders capability is enabled', () => {
    const bot = makeBotConfig({ capabilities: ['orders'] })
    const prompt = buildSystemPrompt(bot)
    expect(prompt).toContain('Инструкции по заказам')
    expect(prompt).toContain('МОЖЕШЬ помогать оформлять заказы')
  })

  it('excludes order instructions when orders capability is not enabled', () => {
    const bot = makeBotConfig({ capabilities: ['support'] })
    const prompt = buildSystemPrompt(bot)
    expect(prompt).not.toContain('Инструкции по заказам')
    expect(prompt).toContain('НЕ принимаешь заказы')
  })
})
