-- AlterTable
ALTER TABLE "Bot" ADD COLUMN     "aiMaxContext" INTEGER NOT NULL DEFAULT 10,
ADD COLUMN     "aiMaxTokens" INTEGER NOT NULL DEFAULT 1024,
ADD COLUMN     "aiModel" TEXT NOT NULL DEFAULT 'gpt-4o-mini',
ADD COLUMN     "aiTemperature" DOUBLE PRECISION NOT NULL DEFAULT 0.7,
ADD COLUMN     "confidenceThreshold" DOUBLE PRECISION NOT NULL DEFAULT 0.6;
